# Stamps the firmware version into generated/openhanko_version.h at build time.
#
# Run as a build step rather than at configure time, so the commit hash cannot go
# stale between a cmake run and a later make. configure_file(COPYONLY) only
# rewrites the header when its contents change, so an unchanged version costs no
# recompile.
#
# The version is PROJECT_VERSION from CMakeLists.txt plus the commit, as semver
# build metadata: 0.2.0+09f45d2. ".dirty" is appended when src/ has uncommitted
# changes — the one thing a signed image must never be without saying so.
# README and doc edits outside src/ do not change the binary, so they do not
# count.
execute_process(COMMAND git -C "${SRC}" rev-parse --short=7 HEAD
  OUTPUT_VARIABLE COMMIT RESULT_VARIABLE rc ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT rc EQUAL 0 OR COMMIT STREQUAL "")
  set(COMMIT "unknown")
else()
  execute_process(COMMAND git -C "${SRC}" status --porcelain --untracked-files=no -- .
    OUTPUT_VARIABLE CHANGES ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT CHANGES STREQUAL "")
    set(COMMIT "${COMMIT}.dirty")
  endif()
endif()

file(WRITE "${OUT}.tmp" "// Generated by version.cmake at build time. Do not edit.
#pragma once
#define OPENHANKO_VERSION \"${VERSION}\"
#define OPENHANKO_COMMIT \"${COMMIT}\"
#define OPENHANKO_VERSION_FULL \"${VERSION}+${COMMIT}\"
")
configure_file("${OUT}.tmp" "${OUT}" COPYONLY)
file(REMOVE "${OUT}.tmp")
